---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://gateway:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
  - job_name: app
    pipeline_stages:
      - multiline:
          firstline: '^\[([^\]]+)\] \w+\.(\w+):.+$'
          max_lines: 1024
      - regex:
          expression: '\[(?P<timestamp>[^\]]+)\] \w+\.(?P<level>\w+):'
      - timestamp:
          source: timestamp
          format: 2006-01-02 15:04:05
          location: Africa/Johannesburg
      - labels:
          level:
      - match:
          selector: '{job="app"} |= "[Event]"'
          pipeline_name: events
          action: keep
          stages:
            - regex:
                expression: '.*[Event] (?P<event_name>[\w.]+)'
    static_configs:
      - targets:
          - localhost
        labels:
          job: app
          __path__: /app/logs/*log
