groups:
  - name: SlackerNews
    interval: 1s
    rules:

      - alert: Excessive Votes
        expr: increase(votes_by_user[1m]) >= 20
        annotations:
          summary: "{{ $labels.user_id }} has cast {{ $value }} votes in the last minute"
        labels:
          severity: warning

      - alert: MySQL Down
        expr: mysql_up < 1
        annotations:
          summary: MySQL is currently not running
        labels:
          severity: critical