global:
  scrape_interval:     2s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'sql_exporter'
    static_configs:
      - targets:
        - 'sql_exporter:9399'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093