global:
  scrape_interval:     1s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'sql_exporter'
    static_configs:
      - targets:
        - 'sql_exporter:9399'
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'prometheus:9090'
  - job_name: 'loki'
    static_configs:
      - targets:
        - 'read:3100'
        - 'write:3100'
  - job_name: 'promtail'
    static_configs:
      - targets:
        - 'promtail:9080'
  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - 'node_exporter:9100'
  - job_name: 'mysqld_exporter'
    static_configs:
      - targets:
        - 'mysqld_exporter:9104'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093