{
 "title": "Tulip NFT Moneymaking Scheme!!",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Logs", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Checkout Requests by Status Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (count_over_time({compose_service=\"nginx\"} |= `POST /api/checkout/save-order` | pattern `<_> HTTP/1.1\" <code> <_>`[1m]))"
    }
   ]
  },
  {
   "title": "Cart Items Added",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(\n  {job=\"app\"}\n    |= `EVENT: Cart`\n    | regexp `EVENT: Cart \\d+ has (?P<count>\\d+) items`\n    | unwrap count\n    | __error__=\"\"\n  [1m]\n)"
    }
   ]
  },
  {
   "title": "Out of Stock Items Added to Cart",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (\n  count_over_time(\n    {job=\"app\"}\n      |= `is out of stock`\n      | regexp `EVENT: Item \"(?P<name>.+)\" is out of stock`\n    [1m]\n  )\n)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}